### PR TITLE
im such a good friend ~ best cam girl

### PR DESCRIPTION
**Pull request by MurfCode**
pls augu qt

### CODE REVIEW

**Comment by MurfCode** [comment]
i mean it works

**Comment by ry0id** [comment]
ye

**Comment by ry0id** [comment]
**i** didn't know you were able to chain them tho

**Comment by ry0id** [comment]
hecc

**Comment by ry0id** [comment]
ok august is prob gone i'm gonna merge

**Comment by MurfCode** [comment]
~~give access~~

**Comment by snarkyllama** [comment]
:eyes:

**Comment by ohlookitsAugust** [comment]
no U

**Pull request merged**
